//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "mdp", table_name = "responses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
    pub response_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub workspace_id: String,
    pub submitted_at: Option<DateTimeWithTimeZone>,
    pub answers: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub survey_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::surveys::Entity",
        from = "(Column::SurveyId, Column::SurveyId, Column::SurveyId)",
        to = "(super::surveys::Column::SurveyId, super::surveys::Column::SurveyId, super::surveys::Column::SurveyId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Surveys,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "(Column::WorkspaceId, Column::WorkspaceId, Column::WorkspaceId)",
        to = "(super::workspaces::Column::WorkspaceId, super::workspaces::Column::WorkspaceId, super::workspaces::Column::WorkspaceId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::surveys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Surveys.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
