//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "mdp", table_name = "stripe_events")]
pub struct Model {
    pub id: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
    pub stripe_event_id: String,
    #[sea_orm(column_type = "Text")]
    pub from_stripe_event_id: String,
    pub attributes: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub event_type: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub workspace_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
