//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "mdp", table_name = "surveys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
    pub survey_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    pub name: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub modified_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub plaintext: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parse_version: Option<String>,
    pub blocks: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::responses::Entity")]
    Responses,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "(Column::UserId, Column::UserId, Column::UserId)",
        to = "(super::users::Column::UserId, super::users::Column::UserId, super::users::Column::UserId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "(Column::WorkspaceId, Column::WorkspaceId, Column::WorkspaceId)",
        to = "(super::workspaces::Column::WorkspaceId, super::workspaces::Column::WorkspaceId, super::workspaces::Column::WorkspaceId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::responses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Responses.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workspaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
