//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "mdp", table_name = "users")]
pub struct Model {
    pub id: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    pub created_at: DateTimeWithTimeZone,
    pub modified_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub email_status: String,
    pub email_confirmed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub confirmation_token: Option<String>,
    pub confirmation_token_expire_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub role: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::surveys::Entity")]
    Surveys,
    #[sea_orm(
        belongs_to = "super::workspaces::Entity",
        from = "(Column::WorkspaceId, Column::WorkspaceId, Column::WorkspaceId)",
        to = "(super::workspaces::Column::WorkspaceId, super::workspaces::Column::WorkspaceId, super::workspaces::Column::WorkspaceId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Workspaces,
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::surveys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Surveys.def()
    }
}

impl Related<super::workspaces::Entity> for Entity {
    fn to() -> RelationDef {
        super::sessions::Relation::Workspaces.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::sessions::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
