//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "mdp", table_name = "workspaces")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub workspace_id: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::responses::Entity")]
    Responses,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::surveys::Entity")]
    Surveys,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::responses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Responses.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::surveys::Entity> for Entity {
    fn to() -> RelationDef {
        super::responses::Relation::Surveys.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::responses::Relation::Workspaces.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::sessions::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::sessions::Relation::Workspaces.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
